version: "3.1"

services:
  deliveries:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: employee1
      POSTGRES_USER: employee
      POSTGRES_DB: deliveries
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
